//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 12:59:35 PM EEST 
//


package com.documet.myapp.otgruzka;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.document.myapp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class DocumentFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.document.myapp
     * 
     */
    public DocumentFactory() {
    }

    /**
     * Create an instance of {@link RootDocument }
     * 
     */
    public RootDocument createDESADV() {
        return new RootDocument();
    }

    /**
     * Create an instance of {@link RootDocument.HEAD }
     * 
     */
    public RootDocument.HEAD createDESADVHEAD() {
        return new RootDocument.HEAD();
    }

    /**
     * Create an instance of {@link RootDocument.HEAD.PACKINGSEQUENCE }
     * 
     */
    public RootDocument.HEAD.PACKINGSEQUENCE createDESADVHEADPACKINGSEQUENCE() {
        return new RootDocument.HEAD.PACKINGSEQUENCE();
    }

    /**
     * Create an instance of {@link RootDocument.HEAD.PACKINGSEQUENCE.POSITION }
     * 
     */
    public RootDocument.HEAD.PACKINGSEQUENCE.POSITION createDESADVHEADPACKINGSEQUENCEPOSITION() {
        return new RootDocument.HEAD.PACKINGSEQUENCE.POSITION();
    }

}
