//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 12:59:35 PM EEST 
//


package com.documet.myapp.otgruzka;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NUMBER" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="DATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DELIVERYDATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ORDERNUMBER" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ORDERDATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DELIVERYNOTENUMBER" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="DELIVERYNOTEDATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="TRANSPORTTYPE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="TRANSPORTERTYPE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="SHIPMENTS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="CAMPAIGNNUMBER" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="HEAD">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SUPPLIER" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="BUYER" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="DELIVERYPLACE" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="SENDER" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="RECIPIENT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="EDIINTERCHANGEID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="PACKINGSEQUENCE">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="HIERARCHICALID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="POSITION" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="POSITIONNUMBER" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="PRODUCT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="PRODUCTIDBUYER" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="DELIVEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="DELIVEREDUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ORDEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="ORDERUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="PRICE" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "number",
    "date",
    "deliverydate",
    "ordernumber",
    "orderdate",
    "deliverynotenumber",
    "deliverynotedate",
    "transporttype",
    "transportertype",
    "shipments",
    "campaignnumber",
    "head"
})
@XmlRootElement(name = "DESADV")
public class RootDocument {

    @XmlElement(name = "NUMBER")
    protected long number;
    @XmlElement(name = "DATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "DELIVERYDATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deliverydate;
    @XmlElement(name = "ORDERNUMBER")
    protected long ordernumber;
    @XmlElement(name = "ORDERDATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar orderdate;
    @XmlElement(name = "DELIVERYNOTENUMBER")
    protected short deliverynotenumber;
    @XmlElement(name = "DELIVERYNOTEDATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deliverynotedate;
    @XmlElement(name = "TRANSPORTTYPE")
    protected byte transporttype;
    @XmlElement(name = "TRANSPORTERTYPE")
    protected byte transportertype;
    @XmlElement(name = "SHIPMENTS")
    protected byte shipments;
    @XmlElement(name = "CAMPAIGNNUMBER")
    protected long campaignnumber;
    @XmlElement(name = "HEAD", required = true)
    protected RootDocument.HEAD head;

    /**
     * Gets the value of the number property.
     * 
     */
    public long getNUMBER() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     */
    public void setNUMBER(long value) {
        this.number = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATE() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATE(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the deliverydate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDELIVERYDATE() {
        return deliverydate;
    }

    /**
     * Sets the value of the deliverydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDELIVERYDATE(XMLGregorianCalendar value) {
        this.deliverydate = value;
    }

    /**
     * Gets the value of the ordernumber property.
     * 
     */
    public long getORDERNUMBER() {
        return ordernumber;
    }

    /**
     * Sets the value of the ordernumber property.
     * 
     */
    public void setORDERNUMBER(long value) {
        this.ordernumber = value;
    }

    /**
     * Gets the value of the orderdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getORDERDATE() {
        return orderdate;
    }

    /**
     * Sets the value of the orderdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setORDERDATE(XMLGregorianCalendar value) {
        this.orderdate = value;
    }

    /**
     * Gets the value of the deliverynotenumber property.
     * 
     */
    public short getDELIVERYNOTENUMBER() {
        return deliverynotenumber;
    }

    /**
     * Sets the value of the deliverynotenumber property.
     * 
     */
    public void setDELIVERYNOTENUMBER(short value) {
        this.deliverynotenumber = value;
    }

    /**
     * Gets the value of the deliverynotedate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDELIVERYNOTEDATE() {
        return deliverynotedate;
    }

    /**
     * Sets the value of the deliverynotedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDELIVERYNOTEDATE(XMLGregorianCalendar value) {
        this.deliverynotedate = value;
    }

    /**
     * Gets the value of the transporttype property.
     * 
     */
    public byte getTRANSPORTTYPE() {
        return transporttype;
    }

    /**
     * Sets the value of the transporttype property.
     * 
     */
    public void setTRANSPORTTYPE(byte value) {
        this.transporttype = value;
    }

    /**
     * Gets the value of the transportertype property.
     * 
     */
    public byte getTRANSPORTERTYPE() {
        return transportertype;
    }

    /**
     * Sets the value of the transportertype property.
     * 
     */
    public void setTRANSPORTERTYPE(byte value) {
        this.transportertype = value;
    }

    /**
     * Gets the value of the shipments property.
     * 
     */
    public byte getSHIPMENTS() {
        return shipments;
    }

    /**
     * Sets the value of the shipments property.
     * 
     */
    public void setSHIPMENTS(byte value) {
        this.shipments = value;
    }

    /**
     * Gets the value of the campaignnumber property.
     * 
     */
    public long getCAMPAIGNNUMBER() {
        return campaignnumber;
    }

    /**
     * Sets the value of the campaignnumber property.
     * 
     */
    public void setCAMPAIGNNUMBER(long value) {
        this.campaignnumber = value;
    }

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link RootDocument.HEAD }
     *     
     */
    public RootDocument.HEAD getHEAD() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link RootDocument.HEAD }
     *     
     */
    public void setHEAD(RootDocument.HEAD value) {
        this.head = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SUPPLIER" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="BUYER" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="DELIVERYPLACE" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="SENDER" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="RECIPIENT" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="EDIINTERCHANGEID" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="PACKINGSEQUENCE">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="HIERARCHICALID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="POSITION" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="POSITIONNUMBER" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="PRODUCT" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="PRODUCTIDBUYER" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="DELIVEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="DELIVEREDUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ORDEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="ORDERUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="PRICE" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "supplier",
        "buyer",
        "deliveryplace",
        "sender",
        "recipient",
        "ediinterchangeid",
        "packingsequence"
    })
    public static class HEAD {

        @XmlElement(name = "SUPPLIER")
        protected long supplier;
        @XmlElement(name = "BUYER")
        protected long buyer;
        @XmlElement(name = "DELIVERYPLACE")
        protected long deliveryplace;
        @XmlElement(name = "SENDER")
        protected long sender;
        @XmlElement(name = "RECIPIENT")
        protected long recipient;
        @XmlElement(name = "EDIINTERCHANGEID")
        protected long ediinterchangeid;
        @XmlElement(name = "PACKINGSEQUENCE", required = true)
        protected RootDocument.HEAD.PACKINGSEQUENCE packingsequence;

        /**
         * Gets the value of the supplier property.
         * 
         */
        public long getSUPPLIER() {
            return supplier;
        }

        /**
         * Sets the value of the supplier property.
         * 
         */
        public void setSUPPLIER(long value) {
            this.supplier = value;
        }

        /**
         * Gets the value of the buyer property.
         * 
         */
        public long getBUYER() {
            return buyer;
        }

        /**
         * Sets the value of the buyer property.
         * 
         */
        public void setBUYER(long value) {
            this.buyer = value;
        }

        /**
         * Gets the value of the deliveryplace property.
         * 
         */
        public long getDELIVERYPLACE() {
            return deliveryplace;
        }

        /**
         * Sets the value of the deliveryplace property.
         * 
         */
        public void setDELIVERYPLACE(long value) {
            this.deliveryplace = value;
        }

        /**
         * Gets the value of the sender property.
         * 
         */
        public long getSENDER() {
            return sender;
        }

        /**
         * Sets the value of the sender property.
         * 
         */
        public void setSENDER(long value) {
            this.sender = value;
        }

        /**
         * Gets the value of the recipient property.
         * 
         */
        public long getRECIPIENT() {
            return recipient;
        }

        /**
         * Sets the value of the recipient property.
         * 
         */
        public void setRECIPIENT(long value) {
            this.recipient = value;
        }

        /**
         * Gets the value of the ediinterchangeid property.
         * 
         */
        public long getEDIINTERCHANGEID() {
            return ediinterchangeid;
        }

        /**
         * Sets the value of the ediinterchangeid property.
         * 
         */
        public void setEDIINTERCHANGEID(long value) {
            this.ediinterchangeid = value;
        }

        /**
         * Gets the value of the packingsequence property.
         * 
         * @return
         *     possible object is
         *     {@link RootDocument.HEAD.PACKINGSEQUENCE }
         *     
         */
        public RootDocument.HEAD.PACKINGSEQUENCE getPACKINGSEQUENCE() {
            return packingsequence;
        }

        /**
         * Sets the value of the packingsequence property.
         * 
         * @param value
         *     allowed object is
         *     {@link RootDocument.HEAD.PACKINGSEQUENCE }
         *     
         */
        public void setPACKINGSEQUENCE(RootDocument.HEAD.PACKINGSEQUENCE value) {
            this.packingsequence = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="HIERARCHICALID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="POSITION" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="POSITIONNUMBER" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="PRODUCT" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="PRODUCTIDBUYER" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="DELIVEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="DELIVEREDUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ORDEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="ORDERUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="PRICE" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hierarchicalid",
            "position"
        })
        public static class PACKINGSEQUENCE {

            @XmlElement(name = "HIERARCHICALID")
            protected byte hierarchicalid;
            @XmlElement(name = "POSITION")
            protected List<RootDocument.HEAD.PACKINGSEQUENCE.POSITION> position;

            /**
             * Gets the value of the hierarchicalid property.
             * 
             */
            public byte getHIERARCHICALID() {
                return hierarchicalid;
            }

            /**
             * Sets the value of the hierarchicalid property.
             * 
             */
            public void setHIERARCHICALID(byte value) {
                this.hierarchicalid = value;
            }

            /**
             * Gets the value of the position property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the position property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPOSITION().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RootDocument.HEAD.PACKINGSEQUENCE.POSITION }
             * 
             * 
             */
            public List<RootDocument.HEAD.PACKINGSEQUENCE.POSITION> getPOSITION() {
                if (position == null) {
                    position = new ArrayList<RootDocument.HEAD.PACKINGSEQUENCE.POSITION>();
                }
                return this.position;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="POSITIONNUMBER" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="PRODUCT" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="PRODUCTIDBUYER" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="DELIVEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="DELIVEREDUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ORDEREDQUANTITY" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="ORDERUNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="PRICE" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "positionnumber",
                "product",
                "productidbuyer",
                "deliveredquantity",
                "deliveredunit",
                "orderedquantity",
                "orderunit",
                "price",
                "description"
            })
            public static class POSITION {

                @XmlElement(name = "POSITIONNUMBER")
                protected byte positionnumber;
                @XmlElement(name = "PRODUCT")
                protected long product;
                @XmlElement(name = "PRODUCTIDBUYER")
                protected int productidbuyer;
                @XmlElement(name = "DELIVEREDQUANTITY")
                protected byte deliveredquantity;
                @XmlElement(name = "DELIVEREDUNIT", required = true)
                protected String deliveredunit;
                @XmlElement(name = "ORDEREDQUANTITY")
                protected float orderedquantity;
                @XmlElement(name = "ORDERUNIT", required = true)
                protected String orderunit;
                @XmlElement(name = "PRICE")
                protected float price;
                @XmlElement(name = "DESCRIPTION", required = true)
                protected String description;

                /**
                 * Gets the value of the positionnumber property.
                 * 
                 */
                public byte getPOSITIONNUMBER() {
                    return positionnumber;
                }

                /**
                 * Sets the value of the positionnumber property.
                 * 
                 */
                public void setPOSITIONNUMBER(byte value) {
                    this.positionnumber = value;
                }

                /**
                 * Gets the value of the product property.
                 * 
                 */
                public long getPRODUCT() {
                    return product;
                }

                /**
                 * Sets the value of the product property.
                 * 
                 */
                public void setPRODUCT(long value) {
                    this.product = value;
                }

                /**
                 * Gets the value of the productidbuyer property.
                 * 
                 */
                public int getPRODUCTIDBUYER() {
                    return productidbuyer;
                }

                /**
                 * Sets the value of the productidbuyer property.
                 * 
                 */
                public void setPRODUCTIDBUYER(int value) {
                    this.productidbuyer = value;
                }

                /**
                 * Gets the value of the deliveredquantity property.
                 * 
                 */
                public byte getDELIVEREDQUANTITY() {
                    return deliveredquantity;
                }

                /**
                 * Sets the value of the deliveredquantity property.
                 * 
                 */
                public void setDELIVEREDQUANTITY(byte value) {
                    this.deliveredquantity = value;
                }

                /**
                 * Gets the value of the deliveredunit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDELIVEREDUNIT() {
                    return deliveredunit;
                }

                /**
                 * Sets the value of the deliveredunit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDELIVEREDUNIT(String value) {
                    this.deliveredunit = value;
                }

                /**
                 * Gets the value of the orderedquantity property.
                 * 
                 */
                public float getORDEREDQUANTITY() {
                    return orderedquantity;
                }

                /**
                 * Sets the value of the orderedquantity property.
                 * 
                 */
                public void setORDEREDQUANTITY(float value) {
                    this.orderedquantity = value;
                }

                /**
                 * Gets the value of the orderunit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getORDERUNIT() {
                    return orderunit;
                }

                /**
                 * Sets the value of the orderunit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setORDERUNIT(String value) {
                    this.orderunit = value;
                }

                /**
                 * Gets the value of the price property.
                 * 
                 */
                public float getPRICE() {
                    return price;
                }

                /**
                 * Sets the value of the price property.
                 * 
                 */
                public void setPRICE(float value) {
                    this.price = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDESCRIPTION() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDESCRIPTION(String value) {
                    this.description = value;
                }

            }

        }

    }

}
